#!/bin/sh
# DEBackup Tool script
DEBUG="Release "
TEMP=$(</lib410/Resources/debackup/temp)
MASTERPATH=$(</lib410/Resources/debackup/master)
PERMASTORE=$(</lib410/Resources/debackup/perma)
INPROGRESS=$(</lib410/Resources/debackup/inprogress)
BINDIR=$(</lib410/Resources/debackup/bindir)
echo "======================================"
echo "You are trying to backup all the debs."
echo "It may take very long, and it depends"
echo "the number of debs installed and the "
echo "speed of your device."
echo "======================================"
echo "What will the backup name be?"
read backupname
echo "PROCESS: backupDebsOnly-getlist / BACKUP_NAME: "$backupname > $INPROGRESS
echo "1/5: Accessing dpkg to get the list..."
total=$(dpkg --get-selections | awk '{print $1}'|grep -v gsc|grep -v "^cy+" | wc -l)
echo " Found " $total " debs to backup."
echo "2/5: Extract to DEB"
echo "PROCESS: backupDebsOnly-extraction / BACKUP_NAME: "$backupname > $INPROGRESS
echo "Extraction: 0%"
for ((i=0; i<total; i++)) do
	( echo y
	echo $i
	 ) | $BINDIR"extractionTool" >&- 2>&-
	previousVal=0
	percent=$(awk "BEGIN { pc=100*${i}/${total}; i=int(pc); print (pc-i<0.5)?i:i+1 }")
	if [ $percent != $previousVal ]; then
		echo "Extraction: "$percent"%"
		previousVal=$percent
	fi
done
echo "Extraction: ["$total"/"$total"]"
cd $TEMP
if [ $DEBUG == "DEBUG_" ]; then
	echo "Backed up list:"
	ls
fi
echo "3/5: Removing Stock Packages from backup..."
echo "PROCESS: backupDebsOnly-eraseStockPackages / BACKUP_NAME: "$backupname > $INPROGRESS
if [ $DEBUG == "DEBUG_" ]; then
	echo "Currently Working:" $(pwd)
	echo "  Erase list: com.ex.substitute, apt7, apt7-key, apt7-lib, base, bash, bzip2, coreutils, coreutils-lib, cydia, {All saurik packages}"
fi
rm com.ex.substitute*
rm apt7*
rm base*
rm bash*
rm bzip2*
rm coreutils*
rm cydia*
rm com.saurik*
cd $MASTERPATH
echo "4/5: Archiving..."
echo "PROCESS: backupDebsOnly-archive / BACKUP_NAME: "$backupname > $INPROGRESS
sleep 2
if [ $DEBUG == "DEBUG_" ]; then
	echo "Currently Working:" $(pwd)
fi
zip -rqq BACKUP_$backupname.zip temp
mv BACKUP_$backupname.zip $PERMASTORE/BACKUP_$backupname.dbk
echo "5/5: Cleaning up..."
echo "PROCESS: backupDebsOnly-cleanup / BACKUP_NAME: "$backupname > $INPROGRESS
if [ $DEBUG == "DEBUG_" ]; then
	echo "Files were not cleaned up because the snapshot is debug version."
elif [ $DEBUG == "Release " ]; then
	$BINDIR"cleanup"
fi
echo "Done."